name: aspen_playground
publish_to: none
environment:
  sdk: ">=2.8.0 <3.0.0"
dependencies:
  aspen: any
  aspen_assets: any
  aspen_web: any
dev_dependencies:
  aspen_builder: any
  build_runner: ^1.9.0
  build_web_compilers: ^2.10.0
dependency_overrides:
  aspen:
    path: ../aspen
  aspen_assets:
    path: ../aspen_assets
  aspen_builder:
    path: ../aspen_builder
  aspen_web:
    path: ../aspen_web
