name: aspen_builder
version: 0.4.0
description: A modern, easy-to-use asset packer (builder package)
homepage: https://github.com/refi64/aspen

environment:
  sdk: '>=2.8.0 <3.0.0'

dependencies:
  analyzer: '>=0.37.0 <0.41.0'
  aspen: ^0.3.0
  aspen_assets: ^0.4.0
  build: ^1.2.0
  csslib: ^0.16.1
  glob: ^1.2.0
  path: ^1.6.0
  source_gen: ^0.9.4+3
  z85: ^0.1.0

dev_dependencies:
  aspen_web: ^0.4.0
  pedantic: ^1.9.0
  build_test: ^1.3.0
  mockito: ^4.1.3
  test: ^1.15.4

dependency_overrides:
  aspen:
    path: ../aspen
  aspen_assets:
    path: ../aspen_assets
  aspen_web:
    path: ../aspen_web
